# Generated by Django 5.2.1 on 2025-08-30 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.URLField(max_length=1000)),
                ('short_url', models.CharField(blank=True, max_length=100, unique=True)),
                ('url_hash', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
