# Generated by Django 5.2.1 on 2025-08-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_url_user_url_user_email_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
