# Generated by Django 5.2.1 on 2025-08-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_url_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='sll_position',
            field=models.IntegerField(default=0),
        ),
    ]
